Authorizeniki/Models/UserLoginModel.cs
namespace Authorizeniki.Models
{
    public class UserLoginModel
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Authorizeniki/Models/UserModel.cs
using System;
using System.Collections.Generic;
using Authorizeniki.Datalayer.Tables;

namespace Authorizeniki.Models
{
    public class UserModel
    {
        public string Login { get; set; }

        public string Password { get; set; }

        public string FirstName { get; set; }

        public string Surname { get; set; }

        public string LastName { get; set; }

        public string SelectedRoleId { get; set; }
    }
}

Authorizeniki/Models/UserPageDto.cs
using System.Collections.Generic;
using Authorizeniki.Datalayer.Tables;

namespace Authorizeniki.Models
{
    public class UserPageDto
    {
        public List<User> UserList { get; set; }
    }
}

Authorizeniki/Controllers/AccountController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Authorizeniki.Datalayer.Repositories;
using Authorizeniki.Datalayer.Tables;
using Authorizeniki.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Authorizeniki.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly string homePage = "/";

        public AccountController(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }

        public IActionResult Login([FromQuery] string returnUrl)
        {
            return View(new UserLoginModel() {ReturnUrl = returnUrl ?? homePage});
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(UserLoginModel userLoginModel)
        {
            var user = userRepository.GetUserByLogin(userLoginModel.Login);

            if (user == null || user.Password != userLoginModel.Password) return Redirect("/Account/AccessDenied");

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, CreateClaims(user));
            return Redirect(userLoginModel.ReturnUrl ?? homePage);
        }

        public IActionResult AccessDenied([FromQuery] string returnUrl)
        {
            ViewData["returnUrl"] = returnUrl ?? homePage;
            return View();
        }

        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/Account/Login");
        }

        private ClaimsPrincipal CreateClaims(User user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Login),
                new Claim(ClaimTypes.Role, user.UserRole.Name),
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            return new ClaimsPrincipal(claimsIdentity);
        }
    }
}

Authorizeniki/Controllers/EventController.cs
using System;
using Authorizeniki.Datalayer.Repositories;
using Authorizeniki.Datalayer.Tables;
using Microsoft.AspNetCore.Mvc;

namespace Authorizeniki.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository eventRepository;

        public EventController(IEventRepository eventRepository)
        {
            this.eventRepository = eventRepository;
        }

        [HttpPut]
        public IActionResult AddEvent([FromBody] Event eEvent)
        {
            eventRepository.Add(eEvent);
            return Ok();
        }

        [HttpGet]
        public IActionResult Get([FromQuery] Guid userId, [FromQuery] DateTime from, [FromQuery] DateTime to)
        {
            return Ok(eventRepository.GetEventsByUserId(userId, from, to));
        }

        [HttpGet]
        public IActionResult CountSalary([FromQuery] Guid userId)
        {
            DateTime date = DateTime.Now;
            var firstDayOfMonth = new DateTime(date.Year, date.Month, 1);
            var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);
            var events = eventRepository.GetEventsByUserId(userId, firstDayOfMonth, lastDayOfMonth);

            if (events.Count == 0)
                throw new Exception($"А чего считать то? юзер {userId} на работе не появлялся в этом месяце!");
            if (events.Count % 2 != 0)
                throw new Exception($"Видимо юзер {userId} еще не ушел с работы, не могу посчитать");

            var salary = 0.0m;
            var hoursInMonth = 160;
            var salaryForHour = events[0]!.User!.UserRole!.Salary / hoursInMonth;
            for (int i = 0; i < events.Count - 1; i += 2)
            {
                var timediff = events[i + 1].EventTime - events[i].EventTime;
                salary += (salaryForHour * timediff.Hours);
            }

            return Ok(salary);
        }
    }
}

Authorizeniki/Controllers/RoleController.cs
using Authorizeniki.Datalayer.Repositories;
using Authorizeniki.Datalayer.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Authorizeniki.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleRepository roleRepository;

        public RoleController(IRoleRepository roleRepository)
        {
            this.roleRepository = roleRepository;
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create([FromForm] Role role)
        {
            roleRepository.Add(new Role()
            {
                Name = role.Name,
                Salary = role.Salary
            });

            return Redirect("/Role/Add");
        }
        
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Add()
        {
            return View();
        }
    }
}

Authorizeniki/Controllers/UserController.cs
using System;
using System.Linq;
using Authorizeniki.Datalayer.Repositories;
using Authorizeniki.Datalayer.Tables;
using Authorizeniki.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Authorizeniki.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly IRoleRepository roleRepository;

        public UserController(IUserRepository userRepository, IRoleRepository roleRepository)
        {
            this.userRepository = userRepository;
            this.roleRepository = roleRepository;
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            var users = userRepository.GetUsers(0, 100);

            return View(new UserPageDto
            {
                UserList = users
            });
        }

        [Authorize(Roles = "admin")]
        public IActionResult Add()
        {
            var selectListItems = roleRepository.GetRoles().Select(item => new SelectListItem()
            {
                Text = item.Name,
                Value = item.Id.ToString()
            }).ToList();
            return View(selectListItems);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create([FromForm] UserModel userCreationModel)
        {
            userRepository.Add(new User()
            {
                Login = userCreationModel.Login,
                Password = userCreationModel.Password,
                Surname = userCreationModel.Surname,
                FirstName = userCreationModel.FirstName,
                LastName = userCreationModel.LastName,
                RoleId = Guid.Parse(userCreationModel.SelectedRoleId)
            });

            return Redirect("/User/Add");
        }

        [HttpGet]
        public IActionResult GetUserById([FromQuery] Guid userId)
        {
            var user = userRepository.GetUserById(userId);
            var result = user is null ? (IActionResult) NotFound() : Ok(user);
            return result;
        }
    }
}

Authorizeniki/Views/Role/Add.cshtml
@model List<SelectListItem>
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div>
    @using (Html.BeginForm("Create", "Role", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="add-table">
            <tr>
                <td>
                    <p>Введите название должности: </p>
                </td>
                <td>
                    <input type="text" name="Name"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Введите оклад: </p>
                </td>
                <td>
                    <input type="number" name="Salary" step="any" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Создать должность"/>
                </td>
                <td></td>
            </tr>
        </table>
    }
</div>

Authorizeniki/Views/User/Add.cshtml
@model List<SelectListItem>
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div>
    @using (Html.BeginForm("Create", "User", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="add-table">
            <tr>
                <td>
                    <p>Введите имя: </p>
                </td>
                <td>
                    <input type="text" name="FirstName"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Введите фамилию: </p>
                </td>
                <td>
                    <input type="text" name="LastName"/>
                </td>
            </tr>

            <tr>
                <td>
                    <p>Введите отчество: </p>
                </td>
                <td>
                    <input type="text" name="Surname"/>
                </td>
            </tr>


            <tr>
                <td>
                    <p>Введите логин: </p>
                </td>
                <td>
                    <input type="text" name="Login"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Введите пароль: </p>
                </td>
                <td>
                    <input type="text" name="Password"/>
                </td>
            </tr>
            <tr>
                <td>
                    <p>Выберите Должность: </p>
                </td>
                <td>
                    @Html.DropDownList("SelectedRoleId", Model,
                        "Выберите Должность")
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Отправить"/>
                </td>
                <td></td>
            </tr>
        </table>
    }
</div>

Authorizeniki/Views/User/Index.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}

@model Authorizeniki.Models.UserPageDto

<div>
    <table class="styled-table">
        <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Фамилия
            </th>
            <th>
                Имя
            </th>
            <th>
                Отчество
            </th>
            <th>
                Логин
            </th>
            <th>
                Пароль
            </th>
            <th>
                Должность
            </th>
            <th>
                ЗПшечка
            </th>
        </tr>
        </thead>
        <tbody>
        @{
            foreach (var user in Model.UserList)
            {
                <tr>
                    <td>
                        @Html.Raw(user.Id)
                    </td>
                    <td>
                        @Html.Raw(user.LastName)
                    </td>
                    <td>
                        @Html.Raw(user.FirstName)
                    </td>
                    <td>
                        @Html.Raw(user.Surname)
                    </td>
                    <td>
                        @Html.Raw(user.Login)
                    </td>
                    <td>
                        @Html.Raw(user.Password)
                    </td>
                    <td>
                        @Html.Raw(user.UserRole.Name)
                    </td>
                    <td>
                        @Html.Raw(user.UserRole.Salary)
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

Authorizeniki/Views/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Авторизационники</title>
    <link rel="stylesheet" href="~/Content/Main.css"/>
</head>
<body>
<table class="navigation-table navigation-table-border">
    <tr>
        <td>
            <h3>
                Авторизационники
            </h3>
        </td>
        <td>
            <h3>
                <a href="/User/Index/">Список пользователей</a>
            </h3>
        </td>
        <td>
            <h3>
                <a href="/User/Add/">Добавить пользователей</a>
            </h3>
        </td>
        <td>
            <h3>
                <a href="/Role/Add/">Добавить должность</a>
            </h3>
        </td>
        <td>
            <h3>
                <a href="/Account/SignOut/">Выход</a>
            </h3>
        </td>
    </tr>
</table>

<div class="container body-content">
    <h1 style="text-align: center">Авторизационники.рф</h1>
    @RenderBody()
    <hr/>
    <footer>
        <p style="text-align: center">&copy; @DateTime.Now.Date.Year - Authorizeniki inc. </p>
    </footer>
</div>
@RenderSection("Scripts", required: false)
</body>
</html>